In [1]:
import numpy as np
import pandas as pd
import gym
from random import randint

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ale_py/roms/utils.py:90: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
  for external in metadata.entry_points().get(self.group, []):


In [ ]:
num_rows = 5
num_cols = 7
pre_booked = 8

In [ ]:
df = pd.DataFrame(np.zeros((num_rows, num_cols)))

In [ ]:
while pre_booked>=0:
    pre_booked -= 1
    row_to_update = np.random.randint(num_rows, size=1)
    col_to_update = np.random.randint(num_cols, size=1)
    print(row_to_update[0], col_to_update[0])
    df.at[row_to_update[0],col_to_update[0]]=1


In [ ]:
df

In [ ]:
df.isin([0]).all()

In [ ]:
df.isin([0]).all().sum()

In [ ]:
test = [i for i in range(1, 5)]
test

In [ ]:
test = gym.spaces.Discrete(6)

In [ ]:
test.contains(0)

In [ ]:
dir(test)

In [ ]:
test.__str__


In [3]:
observation_space = gym.spaces.Box(low=0, high=1, shape=(3, 4), dtype=np.int32)

In [5]:
print( observation_space.sample())

[[1 1 0 0]
 [1 0 1 0]
 [1 0 0 1]]
